### ISSUE TITLE
Коллекция youtube-каналов

### ISSUE THREAD

**Issue by atehnix** [andrew--r/channels#33]
Время от времени пополняю свою коллекцию youtube-каналов по разработке.
На данный момент накопилось примерно полторы сотни каналов.
Делать столько пулл-реквестов считаю не рациональным. Но, тем не менее, что-то полезное для вашего списка наверняка там найдется. ;) 

https://www.youtube.com/channel/UCjMDaMccS5zNZW24xZudffQ/channels

**Comment by andrew--r** [comment]
Спасибо, нашёл пару полезных каналов 👍
