### ISSUE TITLE
Заменить русский язык в README на английский

### ISSUE THREAD

**Issue by in-in** [andrew--r/channels#51]
Сейчас
>Русскоязычные каналы  

но  
>French language channels

Для консистентности всё писать на ~~русском~~ английском. Либо всё что не на английском писать на нативном языке, то есть «_French language channels_» будет «_Chaînes françaises_» пардон, за мой французкий.

**Comment by andrew--r** [comment]
Согласен, спасибо за замечание. Пофиксил в f113906936f11aa1b99f0cebaba2d7a38ca17f19
