### ISSUE TITLE
Mindspace

### ISSUE THREAD

**Issue by sankhadeeproy007** [andrew--r/channels#57]
You missed [Mindspace](https://www.youtube.com/channel/UCSJbGtTlrDami-tDGPUV9-w)! Great tutorials ranging from Laravel to Node/Express and Angular to React to Vue.js

**Comment by LearnWebCode** [comment]
Mindspace is excellent! I just discovered his channel last week; highly recommend it!

**Comment by andrew--r** [comment]
Thank you! Added in 164af4c17bea9f017c6cf07d89f6f3f51b927ed3.
