### ISSUE TITLE
Новый канал по разработке

### ISSUE THREAD

**Issue by AntonGlyadya1** [andrew--r/channels#84]
Здравствуйте. хотелось бы добавить данный канал: 
https://www.youtube.com/channel/UC4omkhNHsYLagT1o6hnmKQw
там автор публикует различные подкасты , уроки, основы компьютерных наук и еще много другого. Также он проводит стримы.

**Comment by andrew--r** [comment]
Привет! Пока на канале мало контента про веб, оставлю ишью открытым, станет больше видео в целом и про веб в частности — добавлю канал.

**Comment by in-in** [comment]
За почти два года на канале появились новые видео про машинное обучение,  С/C++, разработку игр, Java, но не было видео про непосредственно фронтенд. Поэтому, я думаю, есть смысл закрыть эту ишью

**Comment by andrew--r** [comment]
Согласен, закрываю.
